---
title: "Stratification Validation"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 2
    toc_float: true
    df_print: paged
---
    
```{r, include=FALSE}
library(tidyverse)

knitr::opts_chunk$set(fig.width=25, fig.height=6, fig_caption=TRUE)

chr_mapper <- snakemake@params$chr_mapper %>%
  unlist() %>%
  # snakemake will flatten this list when feeding it as a param...oh well :/
  matrix(ncol = 3, byrow = TRUE) %>%
  as_tibble() %>%
  set_names(c("chrom", "chrom_std", "build_key"))

bed_cols <- c("chrom", "start", "end")

read_bed <- function(path) {
  readr::read_tsv(path,
                  comment = "#",
                  col_types = "cii",
                  col_names = bed_cols) %>%
  mutate(region_size = end - start)
}

read_nonN <- function(path) {
  read_bed(path) %>%
    mutate(build_key = path %>% dirname() %>% dirname() %>% basename()) %>%
    left_join(chr_mapper, by = c("chrom", "build_key")) %>%
    select(-chrom)
}

read_strat <- function(path) {
  strat_filename <- basename(path)
  read_bed(path) %>%
    mutate(build_key = path %>% dirname() %>% dirname() %>% basename(),
           ## genome = str_extract(strat_filename, "^[^_]+_(HG[0-9]+)_.bed.gz", 1),
           ## strat_level = str_extract(strat_filename, 
           ##                           if_else(is.na(genome),
           ##                                   "^[^_]+_(.*).bed.gz",
           ##                                   "^[^_]+_HG[0-9]+_(.*).bed.gz"),
           ##                           1),
           strat_name = str_extract(strat_filename, "^[^_]+_(.*).bed.gz", 1)) %>%
    left_join(chr_mapper, by = c("chrom", "build_key")) %>%
    select(-chrom)
}

df_chr_sizes <- snakemake@input$nonN %>%
  map_dfr(read_nonN) %>%
  group_by(chrom_std, build_key) %>%
  summarise(nonN_ref_len = sum(region_size), .groups = "drop")

chr_order <- df_chr_sizes %>%
  pull(chrom_std) %>%
  unique()

chr_build_combinations <- chr_mapper %>%
  expand(build_key, chrom_std = chr_order)

file_list <- snakemake@input$strats %>%
  map(readLines) %>%
  flatten()

read_strats <- function(stype) {
  fs <- keep(file_list, ~ basename(dirname(.x)) == stype)
  if (length(fs) > 0) {
    df <- map_dfr(fs, read_strat)
    all_combos <- chr_build_combinations %>%
      expand(nesting(chrom_std, build_key), strat_name = df$strat_name)
    df %>%
      group_by(build_key, strat_name, chrom_std) %>%
      summarise(total_region = sum(region_size), .groups = "drop") %>%
      # join the full cartesian product of all chromosomes and paths, then fill
      # missing with 0 so that we get an empty space on the graphs indicating
      # zero coverage
      full_join(all_combos, by = c("chrom_std", "strat_name", "build_key")) %>%
      left_join(df_chr_sizes, by = c("chrom_std", "build_key")) %>%
      mutate(strat_type = stype,
             coverage = total_region / nonN_ref_len,
             chrom_std = factor(chrom_std, levels = chr_order)) %>%
      replace_na(list(coverage = 0))
  } else {
    NULL
  }
}

coverage_plot <- function(df, level) {
  cat(sprintf("#### %s\n\n", level))
  p <- df %>%
    ggplot(aes(chrom_std, coverage, fill = build_key)) +
    geom_col(position = "dodge") +
    scale_y_continuous(labels = scales::percent) +
    theme(legend.position = "top",
          text = element_text(size = 30),
          axis.text.x = element_text(angle = 90),
          strip.text.y = element_text(angle = 0),
          panel.spacing.y = unit(2, "lines")) +
    labs(x = NULL,
         fill = "build")
  print(p)
  cat("\n\n")
}

coverage_plots <- function(stype) {
  cat(sprintf("### %s\n\n", stype))
  df <- read_strats(stype)
  if (is.null(df)) {
    cat("None\n\n")
  } else {
    df %>%
      group_by(strat_name) %>%
      group_walk(coverage_plot)
  }
}

```

# Overview

The following plots can be used to sanity-check the completed stratification bed
files. These files can be assumed to:

* be valid bed files
* be sorted
* have no overlapping regions
* have only valid chromosomes
* not intersect with gaps in the reference

# Coverage Plots

## Core

```{r, echo = FALSE, results = "asis"}
walk(snakemake@params$core_levels, coverage_plots)
```

## Other

User-added stratifications

```{r, echo = FALSE, results = "asis"}
walk(snakemake@params$other_levels, coverage_plots)
```
