stratifications:
  CHM13:
    ref:
      src:
        url: https://s3-us-west-2.amazonaws.com/human-pangenomics/T2T/CHM13/assemblies/analysis_set/chm13v2.0.fa.gz
      chr_prefix: chr
    low_complexity:
      # NOTE this is formatted differently from the hg38 version
      rmsk:
        src:
          url: https://s3-us-west-2.amazonaws.com/human-pangenomics/T2T/CHM13/assemblies/annotation/chm13v2.0_RepeatMasker_4.1.2p1.bed
          fmt: nozip
        class_col: 6
      # NOTE this is formatted differently from the hg38 version
      simreps:
        # from here: https://app.globus.org/file-manager?origin_id=9db1f0a6-a05a-11ea-8f06-0a21f750d19b&origin_path=%2Fteam-segdups%2FAssembly_analysis%2FMasked%2F/T2T_CHM13v2_trf.bed
        src:
          filepath: data/CHM13/LowComplexity/T2T-CHM13v2_trf.bed.gz
      # https://t2t-consortium.slack.com/files/ULT7E06GL/F039A96RY84/t2t_censat_chm13v2.0_trackv2.0.bed
      satellites:
        src:
          filepath: data/CHM13/LowComplexity/censat.bed.gz
        skip_lines: 1
    xy:
      # from a slack thread w/ Melissa Wilson
      features:
        x_bed:
          src:
            filepath: data/CHM13/XY/x_features.bed.gz
        y_bed:
          src: 
            filepath: data/CHM13/XY/y_features.bed.gz
        # no ampliconic for now
        regions: [XTR]
      x_par:
        start: [0, 2394410]
        end: [153925834, 154259566]
      y_par:
        start: [0, 2458320]
        end: [62122809, 62460029]
    segdups:
      self_chain: {src: {url: "https://dev.null"}}
      self_chain_link: {src: {url: "https://dev.null"}}
    builds:
      test_autosome:
        chr_filter: [21]
        include:
          low_complexity: true
          xy: false
          map: false
    
  GRCh38:
    ref:
      src:
        url: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz
      chr_prefix: chr
    gap:
      src: 
        url: https://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/gap.txt.gz
    low_complexity:
      rmsk:
        src:
          url: https://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/rmsk.txt.gz
        bed_cols:
          chr: 5
          start: 6
          end: 7
        class_col: 11
      satellites: null
      simreps:
        src: 
          url: https://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/simpleRepeat.txt.gz
    xy:
      features: 
        x_bed:
          src: 
            url: https://raw.githubusercontent.com/SexChrLab/SexChrCoordinates/4ad1faf2b822db6fb89498a750d0b5336703fde3/GRCh38/chrX_genomic_features_GRCh38.bed
            fmt: nozip
        y_bed:
          src: 
            url: https://raw.githubusercontent.com/SexChrLab/SexChrCoordinates/4ad1faf2b822db6fb89498a750d0b5336703fde3/GRCh38/chrY_genomic_features_GRCh38.bed
            fmt: nozip
        regions: [XTR, Ampliconic]
      x_par:
        start: [0, 2781479]
        end: [155701383, 156030895]
      y_par:
        start: [10000, 2781479]
        end: [56887902, 57217415]
    segdups:
      self_chain:
        src: 
          url: https://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/chainSelf.txt.gz
      self_chain_link:
        src: 
          url: https://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/chainSelfLink.txt.gz
    builds:
      test_autosome:
        chr_filter: [21]
        include:
          low_complexity: true
          xy: false
          map: false
      test_xy:
        chr_filter: [23, 24]
        include:
          low_complexity: false
          xy: true
          map: false
