# dynamic-testing-full.yml - testing for full pipeline (meant for dry runs)
#
# the following is a typical large-scale config (in this case which should
# closely match a subset of the v3.1 strats for GRCh38)

stratifications:
  GRCh38-full:
    ref:
      src:
        url: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/references/GRCh38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fasta.gz
        md5: 3a3347eae0893f96ecf495d1c39e2284
      chr_prefix: chr
    gap:
      src: 
        url: https://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/gap.txt.gz
        md5: ab378d85a7f7d2c6a82c635e2a1147f0
      params:
        bed_cols: {chr: 1, start: 2, end: 3}

    low_complexity:
      rmsk:
        src:
          url: https://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/rmsk.txt.gz
          md5: 748c3ba3af01720ffc979ce2cea2c6c1
        params:
          bed_cols: {chr: 5, start: 6, end: 7}
        class_col: 11

      satellites: null

      simreps:
        src: 
          url: https://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/simpleRepeat.txt.gz
          md5: 1269c9fad0881f4309f0cec1ca8a23ff
        params:
          bed_cols: {chr: 1, start: 2, end: 3}

    xy:
      features: 
        x_bed:
          src: 
            url: https://raw.githubusercontent.com/SexChrLab/SexChrCoordinates/4ad1faf2b822db6fb89498a750d0b5336703fde3/GRCh38/chrX_genomic_features_GRCh38.bed
            md5: d3ae5a80022907587fd62f9d6b9f2724
          level_col: 3
        y_bed:
          src: 
            url: https://raw.githubusercontent.com/SexChrLab/SexChrCoordinates/4ad1faf2b822db6fb89498a750d0b5336703fde3/GRCh38/chrY_genomic_features_GRCh38.bed
            md5: 3d9b9c70d4b67052168ace62e4b4693d
          level_col: 3
        xtr: true
        ampliconic: true
      x_par:
        start: [0, 2781479]
        end: [155701383, 156030895]
      y_par:
        start: [10001, 2781479]
        end: [56887902, 57217415]

    segdups:
      superdups:
        src:
          url: https://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/genomicSuperDups.txt.gz
          md5: c04291127b3c7e0bdb88a82193c0f404
        params:
          bed_cols: {chr: 1, start: 2, end: 3}

    functional:
      ftbl_src:
        url: https://ftp.ncbi.nlm.nih.gov/genomes/refseq/vertebrate_mammalian/Homo_sapiens/all_assembly_versions/GCF_000001405.39_GRCh38.p13/GCF_000001405.39_GRCh38.p13_feature_table.txt.gz
        md5: ebc000ea91144e48c8989ebff2219d99
      gff_src:
        url: https://ftp.ncbi.nlm.nih.gov/genomes/refseq/vertebrate_mammalian/Homo_sapiens/all_assembly_versions/GCF_000001405.39_GRCh38.p13/GCF_000001405.39_GRCh38.p13_genomic.gff.gz
        md5: 7468a1ca4285bbf1b09c27d723902291

    builds:
      test-autosome:
        chr_filter: []
        include:
          low_complexity: true
          xy: true
          gc: true
          functional: true
          segdups: true
          union: true
          mappability:
            - {length: 250, mismatches: 0, indels: 0}
            - {length: 100, mismatches: 2, indels: 1}
