stratifications:
  GRCh37:
    ref:
      src:
        url: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/references/GRCh37/hs37d5.fa.gz
        md5: d10eebe06c0dbbcb04253e3294d63efc
      chr_prefix: ''
    gap:
      src: 
        url: https://hgdownload.cse.ucsc.edu/goldenPath/hg19/database/gap.txt.gz
        md5: a24a8e1761a9375497e0853278d34854
      params:
        bed_cols: {chr: 1, start: 2, end: 3}
    low_complexity:
      rmsk:
        src:
          url: https://hgdownload.cse.ucsc.edu/goldenPath/hg19/database/rmsk.txt.gz
          md5: bfed7e64af68efec90b9d419d98a2379
        class_col: 11
        params:
          bed_cols: {chr: 5, start: 6, end: 7}
      satellites: null
      simreps:
        src: 
          url: https://hgdownload.cse.ucsc.edu/goldenPath/hg19/database/simpleRepeat.txt.gz
          md5: 51a26869c10434312c51a20d07c9e963
        params:
          bed_cols: {chr: 1, start: 2, end: 3}
    xy:
      features: 
        x_bed:
          src: 
            url: https://raw.githubusercontent.com/SexChrLab/SexChrCoordinates/4ad1faf2b822db6fb89498a750d0b5336703fde3/hg19/chrX_genomic_features_hg19.bed
            md5: bbe9bf0948e1c87d9aaf22aca432b52e
          level_col: 3
          params:
            sep: "\\s+"
        y_bed:
          src: 
            url: https://raw.githubusercontent.com/SexChrLab/SexChrCoordinates/4ad1faf2b822db6fb89498a750d0b5336703fde3/hg19/chrY_genomic_features_hg19.bed
            md5: d22c3c3c73c9671fc1bcf5914af867ce
          level_col: 3
          params:
            sep: "\\s+"
        xtr: true
        ampliconic: true
      x_par:
        start: [60001, 2699520]
        end: [154931044, 155260560]
      y_par:
        start: [0, 2749806]
        end: [59133470, 59373566]
    segdups:
      superdups:
        src:
          url: https://hgdownload.cse.ucsc.edu/goldenPath/hg19/database/genomicSuperDups.txt.gz
          md5: 7359c7e369589f0e87781c0ec89e0b05
        params:
          bed_cols: {chr: 1, start: 2, end: 3}
    functional:
      ftbl_src:
        url: https://ftp.ncbi.nlm.nih.gov/genomes/refseq/vertebrate_mammalian/Homo_sapiens/all_assembly_versions/GCF_000001405.25_GRCh37.p13/GCF_000001405.25_GRCh37.p13_feature_table.txt.gz
        md5: 382b9c2fb7835d42808bc1cf79a29131
      gff_src:
        url: https://ftp.ncbi.nlm.nih.gov/genomes/refseq/vertebrate_mammalian/Homo_sapiens/all_assembly_versions/GCF_000001405.25_GRCh37.p13/GCF_000001405.25_GRCh37.p13_genomic.gff.gz
        md5: b3f379fc76cd11abf0511f1ec1633251
    builds:
      all:
        chr_filter: []
        include:
          low_complexity: true
          xy: true
          gc: true
          functional: true
          segdups: true
          union: true
          mappability:
            - {length: 250, mismatches: 0, indels: 0}
            - {length: 100, mismatches: 2, indels: 1}
