paths:
  resources: "resources"
  results: "results"
  
ref_url: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz
rmsk_url: https://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/rmsk.txt.gz
simreps_url: https://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/simpleRepeat.txt.gz

XY:
  # TODO lock the commit for these instead of downloading straight from master
  X_features: https://raw.githubusercontent.com/SexChrLab/SexChrCoordinates/4ad1faf2b822db6fb89498a750d0b5336703fde3/GRCh38/chrX_genomic_features_GRCh38.bed
  Y_features: https://raw.githubusercontent.com/SexChrLab/SexChrCoordinates/4ad1faf2b822db6fb89498a750d0b5336703fde3/GRCh38/chrY_genomic_features_GRCh38.bed
  X_PAR: https://raw.githubusercontent.com/lh3/dipcall/master/data/hs38.PAR.bed

segdups:
  self_chain: https://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/chainSelf.txt.gz
  self_chain_link: https://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/chainSelfLink.txt.gz

tools:
  repseq: https://github.com/ndwarshuis/repseq/archive/refs/tags/v1.0.0.tar.gz

