resources:
  - mem_mb=58000
default-resources:
  - mem_mb=1000
set-resources:
  # gem is totally ravenous
  - gem_index:mem_mb=32000
  - gem_mappability:mem_mb=32000
  - gem_to_wig:mem_mb=32000
  # some rules involve large files, so more memory
  - get_nonunique:mem_mb=4000
  - subtract_uniform_repeats:mem_mb=4000
  - subtract_uniform_repeat_compliment:mem_mb=4000
  - filter_sort_rmsk:mem_mb=4000
  - filter_sort_existing:mem_mb=4000
  - filter_TRs:mem_mb=4000
  - unit_test_strats:mem_mb=8000
  - validate_strats:mem_mb=12000
  - run_happy:mem_mb=36000
set-threads:
  - gem_index=16
  - gem_mappability=16
restart-times: 0
rerun-incomplete: True
printshellcmds: True
use-conda: True
